# Generated by Django 3.2.5 on 2023-01-12 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(
                default='Awesome post', max_length=20),
            preserve_default=False,
        ),
    ]
